part of '../data/themes.dart';

class LightAppColors {
  static const primaryColor = Color(0xFF863ED5);
  static const unselectedLabelColor = Color(0xFF8789A3);
  static const labelColor = Color(0xFF672CBC);
  static const primaryColorDark = Color(0xFF240F4F);
  static const primaryColorLight = Color(0xFFC5CAE9);
  static const accentColor = Color(0xFFFFC107);
  static const primaryTextColor = Color(0xFF212121);
  static const secondaryTextColor = Color(0xFF757575);
  static const dividerColor = Color(0xFFBBC4CE);
  static const tabbarDividerColor = Color(0x1A8789A3);
  static const scaffoldBackgroundColor = Color(0xFFFFFFFF);
  static const backgroundColor = Color(0xFFF5F5F5);
  static const errorColor = Color(0xFFD32F2F);
  static const successColor = Color(0xFF388E3C);
  static const warningColor = Color(0xFFFFA000);
  static const infoColor = Color(0xFF1976D2);
  static const disabledColor = Color(0xFFBDBDBD);
  static const iconColor = Color(0xFF8789A3);
  static const shadowColor = Color(0x44000000);
  static const cardColor = Color(0x0D121931);
  static const cardColorDark = Color(0xFF000000);
  static const cardColorLight = Color(0xFFFFFFFF);
  static const buttonColor = Color(0xFF3F51B5);
  static const buttonColorDisabled = Color(0xFF9E9E9E);
  static const buttonColorDark = Color(0xFF303F9F);
  static const buttonColorLight = Color(0xFFC5CAE9);
  static const buttonTextColor = Color(0xFFFFFFFF);
  static const buttonTextColorDisabled = Color(0xFFBDBDBD);
  static const buttonTextColorDark = Color(0xFF000000);
  static const buttonTextColorLight = Color(0xFF000000);
  static const buttonColorHighlight = Color(0xFFE0E0E0);
  static const buttonColorHighlightDark = Color(0xFF616161);
  static const buttonColorHighlightLight = Color(0xFFE0E0E0);
  static const buttonColorBorder = Color(0xFF000000);
  static const buttonColorBorderDisabled = Color(0xFF9E9E9E);
  static const buttonColorBorderDark = Color(0xFF303F9F);
  static const buttonColorBorderLight = Color(0xFFC5CAE9);
}
