# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Islamic App"
  lane :firebase_android_app_distribution do
      sh "flutter clean"
      sh "flutter build apk --release"
      release = firebase_app_distribution(
        app: "1:495302383021:android:70fb38c6f1ecca7828fd24",
        firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
        testers: "yara1assad@gmail.com",
        upload_timeout: 3600, # Increase timeout to 1 hour (3600 seconds)
        release_notes: "Lots of amazing new features to test out!"
      )
  end
end
